table dim_services
	lineageTag: d9509f03-9c0d-4c80-a502-98994083a659

	column Customer_ID
		dataType: string
		lineageTag: ab8b79c3-4c97-4cd3-b862-ec6e169acad9
		summarizeBy: none
		sourceColumn: Customer_ID

		annotation SummarizationSetBy = Automatic

	column Has_Phone_Service
		dataType: string
		lineageTag: 1294108f-3dba-4e17-8972-73ce75d2ccbb
		summarizeBy: none
		sourceColumn: Has_Phone_Service

		annotation SummarizationSetBy = Automatic

	column Has_Multiple_Lines
		dataType: string
		lineageTag: dee3f179-09a6-4eaf-82d4-e0ea8b69710b
		summarizeBy: none
		sourceColumn: Has_Multiple_Lines

		annotation SummarizationSetBy = Automatic

	column Internet_Service_Type
		dataType: string
		lineageTag: 84322729-7168-42b1-ab16-ef27f9b5d416
		summarizeBy: none
		sourceColumn: Internet_Service_Type

		annotation SummarizationSetBy = Automatic

	column Has_Online_Security
		dataType: string
		lineageTag: c6ddc665-2ac7-4634-b151-1788e3f7d96e
		summarizeBy: none
		sourceColumn: Has_Online_Security

		annotation SummarizationSetBy = Automatic

	column Has_Online_Backup
		dataType: string
		lineageTag: 5cdc2f1e-b163-45e7-9ba8-6d36daab76d5
		summarizeBy: none
		sourceColumn: Has_Online_Backup

		annotation SummarizationSetBy = Automatic

	column Has_Device_Protection
		dataType: string
		lineageTag: bbe35b4d-0d67-4439-ab96-d3ec7049c7e8
		summarizeBy: none
		sourceColumn: Has_Device_Protection

		annotation SummarizationSetBy = Automatic

	column Has_Tech_Support
		dataType: string
		lineageTag: d806c739-1229-49e7-8dd3-f6bfdea5124c
		summarizeBy: none
		sourceColumn: Has_Tech_Support

		annotation SummarizationSetBy = Automatic

	column Has_Streaming_TV
		dataType: string
		lineageTag: 4df40469-810e-40b4-a016-8c8d170207ad
		summarizeBy: none
		sourceColumn: Has_Streaming_TV

		annotation SummarizationSetBy = Automatic

	column Has_Streaming_Movies
		dataType: string
		lineageTag: 5290b262-ccd3-465b-9f85-da63d67ee681
		summarizeBy: none
		sourceColumn: Has_Streaming_Movies

		annotation SummarizationSetBy = Automatic

	/// Internet service type with 'No' replaced by 'No internet service'
	column Internet_Service_Type_Updated = IF(dim_services[Internet_Service_Type] = "No", "No internet", dim_services[Internet_Service_Type])
		dataType: string
		lineageTag: d8b55554-e7fb-4038-91dc-2764bbef34fe
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition dim_services = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\USER\Downloads\NexaLink_Churn_PowerBI.xlsx"), null, true),
				    dim_services_Sheet = Source{[Item="dim_services",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dim_services_Sheet,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Customer_ID", type text}, {"Has_Phone_Service", type text}, {"Has_Multiple_Lines", type text}, {"Internet_Service_Type", type text}, {"Has_Online_Security", type text}, {"Has_Online_Backup", type text}, {"Has_Device_Protection", type text}, {"Has_Tech_Support", type text}, {"Has_Streaming_TV", type text}, {"Has_Streaming_Movies", type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type1","Yes","1",Replacer.ReplaceText,{"Has_Phone_Service"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","No","0",Replacer.ReplaceText,{"Has_Phone_Service"})
				in
				    #"Replaced Value1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

