/// Dedicated table to store all DAX measures for the NexaLink Churn Analysis project
table 'Measure Table'
	lineageTag: b5cba92f-f6aa-4c5d-9c19-142b096d09d8

	measure 'Total Number of Customers' = DISTINCTCOUNT(fact_churn[Customer_ID])
		formatString: 0
		displayFolder: Core KPIs
		lineageTag: 6df22c83-6f7e-4dc6-b6f6-7787e9e5e043

	measure 'Churned Customers' =
			
			CALCULATE(
			    DISTINCTCOUNT(fact_churn[Customer_ID]),
			    fact_churn[Churned] = "1"
			)
		formatString: 0
		displayFolder: Core KPIs
		lineageTag: dc6c9962-30d1-4c8f-be8b-0c04e1bf9f20

	measure 'Retained Customers' =
			
			CALCULATE(
			    DISTINCTCOUNT(fact_churn[Customer_ID]),
			    fact_churn[Churned] = "0"
			)
		formatString: 0
		displayFolder: Core KPIs
		lineageTag: 6ae2a6ff-cf88-4754-bc34-b608fa66d1bf

	measure 'Churn Rate%' = ```
			
			    DIVIDE(
			        [Churned Customers],
			        [Total Number of Customers],
			        0
			    )
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Core KPIs
		lineageTag: 16815f19-357e-4d0f-941c-3c1de7a87746

	measure 'Retention Rate%' = ```
			
			    1- [Churn Rate%]
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Core KPIs
		lineageTag: 494400c2-0850-407a-ba3f-9261cbfde590

	measure 'Total Number of Non-Senior Citizens' =
			
			CALCULATE(
			    COUNT(dim_customer[Senior Citizen Category]),
			    dim_customer[Senior Citizen Category] = "Non-senior Citizen"
			    )
		formatString: 0
		displayFolder: Demographics
		lineageTag: bdc8d32a-54df-4b5f-97b0-170771c69856

	measure 'Total Number of Senior Citizens' =
			
			[Total Number of Customers] - [Total Number of Non-Senior Citizens]
		formatString: 0
		displayFolder: Demographics
		lineageTag: 6215d487-b993-42ee-a0cf-d4d109ef9be5

	measure 'Senior Churn Rate %' = ```
			
			    CALCULATE(
			        [Churn Rate%],
			        dim_customer[Senior Citizen Category] = "Senior"
			    )
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Demographics
		lineageTag: a54972c6-59cb-4d82-b902-bbe144b7fbd9

	/// Churn rate for non-senior citizens: churned non-seniors divided by total non-seniors
	measure 'Non-Senior Churn Rate %' = ```
			
			    CALCULATE(
			        [Churn Rate%],
			        dim_customer[Senior Citizen Category] = "Non-senior"
			    )
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Demographics
		lineageTag: 86fb9bca-b87f-4e69-86fd-2aae4c0b92b8

	measure 'Average Tenure' =
			
			AVERAGE(dim_customer[Tenure_Months])
		displayFolder: Core KPIs
		lineageTag: babb8c6b-c283-46d3-940d-bc40f15d0548

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% of All Churned Customers' = ```
			
			// Tells us how much the band contributes to all the churned Customers 
			VAR Total_Customers = CALCULATE([Churned Customers], REMOVEFILTERS(dim_customer))
			VAR Pct_Churned = DIVIDE( [Churned Customers], Total_Customers)
			
			RETURN
			    Pct_Churned
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Core KPIs
		lineageTag: bd0975bd-370e-47d0-8818-be97e116803d

	measure 'Average Monthly Charge' = ```
			
			    AVERAGE(dim_billing[Monthly_Charge_USD])
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Core KPIs
		lineageTag: e159be68-dbaf-40df-897f-6b3985559743

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Average Total Charges' = ```
			
			    AVERAGE(dim_billing[Total_Charge_USD])
			    
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Core KPIs
		lineageTag: 9edbbd4a-4115-4c21-b15d-3beffd7879d6

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Median Monthly Charges' = ```
			
			
			    MEDIAN(dim_billing[Monthly_Charge_USD])
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Core KPIs
		lineageTag: 162e8253-eb1a-422c-a0e0-b131a9e110bb

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Median Total Charges' = ```
			
			
			    MEDIAN(dim_billing[Total_Charge_USD])
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Core KPIs
		lineageTag: 5d58109d-27d2-476e-b535-1f61269478f0

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure '% of Total Customers' = ```
			
			
			    VAR Total_Customers = CALCULATE([Total Number of Customers], ALL(dim_customer))
			    VAR Pct_of_Customers = DIVIDE( [Total Number of Customers], Total_Customers , 0)
			    RETURN
			     Pct_of_Customers
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Core KPIs
		lineageTag: 1744a669-81f0-4277-beb9-96d42d1bba3f

	measure 'Totally Monthly Charges' =
			
			SUM(dim_billing[Monthly_Charge_USD])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Core KPIs
		lineageTag: 337a657f-7f0b-4ca8-8125-df22c7b80f89

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Amount Lost(Monthly) to Churn' = ```
			
			    CALCULATE(
			        SUM(dim_billing[Monthly_Charge_USD]),
			         fact_churn[Churn_Updated] = "Churned"
			    )
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Financial Impact
		lineageTag: 8ff62301-d130-4a39-a85d-86c76a931612

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure Zero_Pct = 0
		formatString: 0%;-0%;0%
		displayFolder: Labels & Formatting
		lineageTag: 5be91391-3224-4e88-86ee-0657ddd78ac2

	measure 100_Pct = 0.55
		formatString: 0%;-0%;0%
		displayFolder: Labels & Formatting
		lineageTag: e5fcf5b2-1b94-4456-8086-a5ec835d2d69

	measure Zero_Number = 0
		formatString: 0
		displayFolder: Labels & Formatting
		lineageTag: 97d450e8-4fd2-4e7c-9cda-f54d15cbb5f6

	measure 'Churn Ratio' = ```
			
			VAR Pct_All_Churned_Customers = 
			    [% of All Churned Customers] * 100 
			
			VAR Round_Up = ROUND(Pct_All_Churned_Customers,0)
			
			RETURN
			Round_Up
			```
		displayFolder: Labels & Formatting
		lineageTag: 74750c4f-411d-466d-aaa7-3f90ba24a35b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Customer Ratio' = ```
			
			    VAR Pct_All_Customers = 
			        [% of All Churned Customers] * 100
			    
			    VAR Rnd_Up = ROUNDUP(Pct_All_Customers,0)
			
			RETURN
			Rnd_Up
			```
		displayFolder: Labels & Formatting
		lineageTag: c1fc8df2-a306-4e04-8894-8e716614c0ef

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% of All Churned Retained' = ```
			
			// Tells us how much the band contributes to all the churned Customers 
			VAR Total_Customers = CALCULATE([Retained Customers], REMOVEFILTERS(dim_customer))
			VAR Pct_Retained = DIVIDE( [Retained Customers] ,Total_Customers)
			
			RETURN
			    Pct_Retained
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Core KPIs
		lineageTag: 09c03e95-71a7-49c4-8998-c67399099f08

	measure Pct_Diff_Churn = [100_Pct] - [% of All Churned Customers]
		displayFolder: Labels & Formatting
		lineageTag: 07f23f76-f467-425a-aa57-798bb63fa65e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Text of All churned' = ```
			
			    " | " & FORMAT([% of All Churned Customers], "0.0%") & " of all churn"
			```
		displayFolder: Labels & Formatting
		lineageTag: ef92a0ca-3a03-4dd7-8d9e-b4f1d864eca9

	measure 'Labels Placeholder' = ```
			0 
			```
		formatString: 0
		displayFolder: Labels & Formatting
		lineageTag: 016a9eed-ed34-4500-81c9-2e2aee4827d4

	measure 'Labels Bar Chart - Subcategories' = ```
			
			
			    SELECTEDVALUE(dim_billing[Contract_Type])
			```
		displayFolder: Labels & Formatting
		lineageTag: 1880b573-7c22-4391-8280-5be5ed8836a2

	measure 60_Pct = 0.58
		displayFolder: Labels & Formatting
		lineageTag: 68f88e3d-b816-4fbd-aa02-13bc2d50f151

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 200_Pct = 1.4
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Labels & Formatting
		lineageTag: 1249fb6a-5228-4d68-b403-b06e33f4efe8

	measure 'Dashboard Insights' = ```
			
			UNICHAR(8226) & " Month-to-month customers churn at 15× the rate of two-year customers and account for 88.6% of all customers lost." & UNICHAR(10) &
			UNICHAR(8226) & "  Fiber optic customers churn at 41.89% and contribute 69.4% of all churned customers despite being only 44% of the base.
			" & 
			UNICHAR(8226) & " Raising just one support ticket triples churn probability from 19.69% to 65% — the first ticket is the most critical retention moment." & UNICHAR(10) &
			UNICHAR(8226) & " NexaLink's highest-risk profile combines all three drivers: fiber optic service, month-to-month contract, and active support tickets."
			```
		displayFolder: Labels & Formatting
		lineageTag: b0c4236b-bc1c-4f73-9374-35a1613f70f4

	measure 'Extra Space In Bar Chart(Citizen)' = 1
		formatString: 0
		displayFolder: Demographics
		lineageTag: 81c6c501-6b79-4143-b861-ab3280e16e9d

	measure 'Extra Space In Bar Chart(Gender)' = 0.7
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Demographics
		lineageTag: f613553b-65fc-4c66-8a5a-68d8f1805a34

	measure Hundred_Pct = ```
			1 
			```
		formatString: 0
		displayFolder: Labels & Formatting
		lineageTag: 96d39da9-93e6-40da-8944-3e8e0f4d6192

	measure 'Measure 2'
		isHidden
		displayFolder: Labels & Formatting
		lineageTag: ad531f54-d9c2-4f97-9d5e-1f12f71b5ac5

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure 'Churn Rate Label' =
			
			"Churn Rate : " & FORMAT([Churn Rate%], "0.00%" )
		displayFolder: Labels & Formatting
		lineageTag: 2147f811-58bc-4cbf-87e8-62f5d5fe089a

	measure 'Retained Customer Label' = ```
			
			    "Retained : " & [Retained Customers]
			```
		displayFolder: Labels & Formatting
		lineageTag: 6f401f6e-4c6a-4508-9847-bba4870c6de9

	measure 'Churned Customer Label' = ```
			
			    "Churned : " & [Churned Customers]
			```
		displayFolder: Labels & Formatting
		lineageTag: dd600068-0d00-4457-ab2f-4236bee58134

	measure One_ = 1
		formatString: 0
		displayFolder: Labels & Formatting
		lineageTag: 2ac8981a-ccc2-42df-8bf3-67bc723d99f4

	/// Finds the maximum churn rate grouped by Partners & Dependants and multiplies by 1.5 to create dynamic spacing in bar charts
	measure 'Dynamic Space Measure For Bar Chart' =
			MAXX(
			    SUMMARIZE(
			        'fact_churn',
			        'dim_customer'[Partners & Dependents],
			        "MaxChurnRate", [Churn Rate%]
			    ),
			    [MaxChurnRate]
			) * 2
		displayFolder: Demographics
		lineageTag: c573061a-ec03-48df-b80d-e11f9b899f3b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Dynamic Space Measure For Bar Chart(Retained)' =
			MAXX(
			    SUMMARIZE(
			        'fact_churn',
			        'dim_customer'[Senior Citizen Category],
			        "MaxRetained", [Retained Customers]
			    ),
			    [MaxRetained]
			) * 1.8
		displayFolder: Demographics
		lineageTag: 88621ad8-cc7d-4a65-a7e0-859a55df5d3c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Senior VS Non-senior Insights' = ```
			
			
			UNICHAR(11166) & " Seniors are 16.2% of the base but account for 25.5% of all churned customers." & UNICHAR(10) &
			UNICHAR(11166) & "A senior is 1.77× more likely to churn than a non-senior customer." & UNICHAR(10) &
			UNICHAR(11166) & " Senior churn costs NexaLink $38,420 monthly — 27.6% of total revenue loss. "
			
			
			```
		displayFolder: Demographics
		lineageTag: 7fea7b8d-9dc5-43cd-9085-7043cbd0c90d

	measure 'Senior vs Non-Senior Churn Reference Label' = ```
			
			    VAR Val= FORMAT([Non-Senior Churn Rate %], "0.00%")
			
			    RETURN
			    UNICHAR(11166) & " VS " & Val & " Non-Senior "
			```
		displayFolder: Demographics
		lineageTag: 7e8852bc-ddfd-4c09-befa-d0af7954db53

	measure 'Gender Churn Gap' = ```
			
			VAR _Female_Churn = CALCULATE([Churn Rate%], dim_customer[Gender] = "Female") 
			VAR _Male_Churn   = CALCULATE([Churn Rate%], dim_customer[Gender] = "Male") 
			VAR _Gap          = (_Female_Churn - _Male_Churn) * 100 
			RETURN 
			FORMAT(_Gap, "0.00""pp""")
			
			```
		displayFolder: Demographics
		lineageTag: 65a88aa9-802c-462f-8d86-95d16fa79008

	measure 'Senior VS Non-Senior KPI (Label 2)' =
			
			UNICHAR(11166) & " 1.77×" &UNICHAR(8593) &" higher churn risk"
		displayFolder: Demographics
		lineageTag: 9ad46d69-2db4-4020-90a5-8d67f58072ed

	measure 'Gender Gap Label' = ```
			
			    VAR FemaleChurn = FORMAT(CALCULATE( [Churn Rate%], dim_customer[Gender] = "Female"), "0.00%")
			    VAR MaleChurn = FORMAT(CALCULATE( [Churn Rate%], dim_customer[Gender] = "Male"), "0.00%" )
			
			    RETURN
			    UNICHAR(11166) & " Female " & FemaleChurn & " vs" & " Male " & MaleChurn
			
			```
		displayFolder: Demographics
		lineageTag: 13edf17d-c301-49d4-bdba-6e62d634667d

	measure 'Gender Gap Label_2' =
			
			UNICHAR(11166) & " Not significant"
		displayFolder: Demographics
		lineageTag: 5617c05a-1c20-4e42-bb40-a1c326f5d5e1

	measure 'No of Customers with Dependents' = ```
			
			    CALCULATE([Total Number of Customers],
			      dim_customer[Has_Dependants_Updated] = "Yes"
			    )
			```
		formatString: 0
		displayFolder: Demographics
		lineageTag: 93704d29-3d74-4f46-af0a-f05f2e4bb497

	measure '% of Customers with dependants' = ```
			
			    Var DependantsPct = FORMAT(CALCULATE([% of Total Customers], dim_customer[Has_Dependants_Updated] = "Yes"), "0%")
			    
			    RETURN
			    UNICHAR(11166) & " " & DependantsPct & " of Total Customers"
			        
			```
		displayFolder: Demographics
		lineageTag: 18f995fd-e495-4c40-8e86-6f99ea3b5000

	measure 'No of Customers without Dependents' = ```
			
			    CALCULATE([Total Number of Customers],
			      dim_customer[Has_Dependents]= 0
			    )
			```
		formatString: 0
		displayFolder: Demographics
		lineageTag: e97ab7fc-112e-4556-9265-8ab6e0f144cd

	measure 'Customer without Dependants Label' = ```
			
			    UNICHAR(11166) & " Vs " & [No of Customers without Dependents] & " Customer without dependants"
			```
		displayFolder: Demographics
		lineageTag: 6f2867e8-1e7b-4dd0-98b6-d8d977ca0e32

	measure 'Customers with Partners' = ```
			
			    CALCULATE([Total Number of Customers],
			      dim_customer[Has_Partner_Update] = "Yes"
			    )
			```
		formatString: 0
		displayFolder: Demographics
		lineageTag: 563330b7-d319-4d92-a140-6cf22cc2a020

	measure 'Customers without Partners' = ```
			
			    CALCULATE([Total Number of Customers],
			      dim_customer[Has_Partner_Update] = "No"
			    )
			```
		formatString: 0
		displayFolder: Demographics
		lineageTag: 0e06bbb7-286c-4faf-90c1-b1832424ecbd

	measure 'Customer without Dependents Label 1' = ```
			
			VAR Pct_of_Dependents = 
			    FORMAT(CALCULATE([% of Total Customers], 
			    dim_customer[Has_Dependents] = 0
			    ), "0%")
			
			RETURN
			UNICHAR(11166) & " " & Pct_of_Dependents & " of base customers "
			
			
			```
		displayFolder: Demographics
		lineageTag: 96723112-83c4-43b4-85ea-cea9831a1b38

	measure 'Customer withot Dependents Label 2' = ```
			
			        VAR WithDependentChurn = CALCULATE([Churn Rate%], dim_customer[Has_Dependents] = 1) *100
			        VAR WithoutDependentChurn = CALCULATE([Churn Rate%], dim_customer[Has_Dependents] = 0) * 100
			        VAR Ratio = FORMAT(DIVIDE( WithoutDependentChurn, WithDependentChurn),"0.00")
			
			        RETURN
			            UNICHAR(11166) & " " & Ratio & "x" & UNICHAR(8593) & " higher churn likelyhood"
			```
		displayFolder: Demographics
		lineageTag: bbca95f7-1c84-4ecb-a36c-bd25f2c3baa6

	measure 'Customers without Partners Label 1' = ```
			
			    Var WithoutPartnersPct =    FORMAT(CALCULATE( [% of All Churned Customers], dim_customer[Has_Partner_Update] = "No"), "0.00%")
			
			    RETURN
			   UNICHAR(11166)& " Accounts for " & WithoutPartnersPct & " of churn"
			
			
			```
		displayFolder: Demographics
		lineageTag: 65f664af-b7fc-49a6-ba9f-c7860cdfb4da

	measure 'Customers without Partners Label 2' = ```
			
			        VAR WithPartnersChurn = CALCULATE([Churn Rate%], dim_customer[Has_Partner_Update] = "Yes") *100
			        VAR WithoutPartners = CALCULATE([Churn Rate%], dim_customer[Has_Partner_Update] = "No") * 100
			        VAR Ratio = FORMAT(DIVIDE( WithoutPartners, WithPartnersChurn),"0.00")
			
			        RETURN
			            UNICHAR(11166) & " " & Ratio &"x"& UNICHAR(8593) &" higher churn likelyhood"
			```
		displayFolder: Demographics
		lineageTag: 58b75fdb-fcf7-464f-b3b4-d6d57aa0adb8

	measure 'Gender Analysis Title' = ```
			
			    VAR _Spacing = REPT(UNICHAR(160), 10)
			    RETURN
			    _Spacing & "Gender Analysis"
			```
		displayFolder: Demographics
		lineageTag: b6bc8955-a08d-4960-8ec8-73ff2f1c3f63

	measure FakeSpace = ```
			UNICHAR(8203) & REPT(" ", 20) 
			
			```
		displayFolder: Labels & Formatting
		lineageTag: d4ec0bdd-a432-40b8-869c-9336740e3f77

	measure 'Average Tenure Months' = ```
			
			    AVERAGE(dim_customer[Tenure_Months])
			```
		displayFolder: Tenure
		lineageTag: 621d60bb-a61f-4b53-9c1a-fff9fa368bfc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Months_Label = " months"
		displayFolder: Tenure
		lineageTag: 1332bc58-7cb3-4e4b-a05b-c6feb99debd4

	measure 'Dynamic Space Measure For Bar Chart(Tenure Months)' =
			MAXX(
			    SUMMARIZE(
			        'fact_churn',
			        fact_churn[Churn_Updated],
			        "Avg Months", [Average Tenure Months]
			    ),
			    [Avg Months]
			) * 1.8
		displayFolder: Tenure
		lineageTag: 411bf221-95f1-43bb-b444-cbd6347d7fcf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Dynamic Space Measure For Bar Chart(Tenure Months_ChurnRate)' =
			MAXX(
			    SUMMARIZE(
			        'dim_customer',
			          dim_customer[Tenure_band]  ,
			        "ChurnPct", [Churn Rate%]
			    ),
			    [ChurnPct]
			) * 1.2
		displayFolder: Tenure
		lineageTag: 79bb46ed-50ef-4c1e-b805-e75d3730f211

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avergae Tenure Gap' = ```
			
			    VAR Avg_Churned = 
			            CALCULATE( [Average Tenure Months], fact_churn[Churn_Updated] = "Churned")
			      VAR Avg_Retained = 
			            CALCULATE( [Average Tenure Months], fact_churn[Churn_Updated] = "Retained")
			
			    RETURN
			    Avg_Retained - Avg_Churned 
			```
		displayFolder: Tenure
		lineageTag: 941032da-81c8-43d1-8c7e-4d5821f15fc6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Tenure Gap Label' = ```
			
			    UNICHAR(11166) & " Retained customers stay  3.8x longer"
			```
		displayFolder: Tenure
		lineageTag: 01a67c57-3565-4631-bec4-1ebe27bed2a0

	/// Calculates the median tenure in months for all customers
	measure 'Median Tenure (Months)' = MEDIAN(dim_customer[Tenure_Months])
		displayFolder: Tenure
		lineageTag: 701b1aa2-5ab8-40bc-a432-cbddc34fed45

	measure 'Median Tenure(Months) Label' = ```
			
			UNICHAR(11166) &  
			     " 50% of churn occurs before month " & CALCULATE([Median Tenure (Months)], fact_churn[Churn_Updated] = "Churned")
			```
		displayFolder: Tenure
		lineageTag: 35f167c8-8593-40a0-821c-582cfd1697e1

	measure 'Post Yr 1 churn rate Label' =
			
			
			UNICHAR(11166) & " Drops " & FORMAT([Churn Rate%], "0.00%")  &" after year 1 survival"
		displayFolder: Tenure
		lineageTag: 9194cdca-91bc-4919-b5e8-5d0c1250af00

	measure 'Year 1 & 2_Revenue_Loss' =
			
			CALCULATE(
			    [Amount Lost(Monthly) to Churn],
			    dim_customer[Tenure_Months] >= 0 && dim_customer[Tenure_Months] <= 24)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Tenure
		lineageTag: 1af2054b-672e-442a-8072-d2ccd64dc33b

	measure 'Year 1 &2 Label' = ```
			
			   UNICHAR(11166) & " " & FORMAT(DIVIDE( [Year 1 & 2_Revenue_Loss], [Amount Lost(Monthly) to Churn]),"0.0%") & " of churn losses occurs before month 24"
			```
		displayFolder: Tenure
		lineageTag: f8122ca9-01cd-4663-a1f7-bed86825af40

	measure 'High Risk Tenure band' =
			
			
			MAXX(
			    SUMMARIZE(dim_customer, dim_customer[Tenure_band], "Churn Rate", [Churn Rate%]), [Churn Rate])
		displayFolder: Tenure
		lineageTag: 1cd08157-add8-483f-be7e-2ae2a06a538e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Returns the tenure band with the highest churn rate
	measure 'Highest Churn Tenure Band' = ```
			
			VAR MaxChurnRate = 
			    MAXX(
			        VALUES('dim_customer'[Tenure_band]),
			        [Churn Rate%]
			    )
			RETURN
			    CALCULATE(
			        SELECTEDVALUE('dim_customer'[Tenure_band]),
			        FILTER(
			            VALUES('dim_customer'[Tenure_band]),
			            [Churn Rate%] = MaxChurnRate
			        )
			    )
			```
		displayFolder: Tenure
		lineageTag: 88b57d3e-756e-48dd-9738-1cb4a1caaa99

	measure 'Churn Rate Line' = [Churn Rate%]
		displayFolder: Tenure
		lineageTag: 087a7c62-61ed-4dab-a04a-a9b75306362d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Dynamic Space Measure For Bar Chart(% of Total by tenure band)' =
			
			MAXX(VALUES(dim_customer[Tenure_band]),[% of Total Customers]) * 1.3
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Tenure
		lineageTag: 5228a846-55a9-48b8-a73c-88c52e3aa0cb

	measure 'Average Tenure Text (Retained)' =
			
			FORMAT(
			    CALCULATE(AVERAGE(dim_customer[Tenure_Months]), fact_churn[Churn_Updated] = "Retained"), "0")
		displayFolder: Tenure
		lineageTag: f64f53db-68a7-40d8-8833-751f7e011eba

	measure 'Average Tenure Text (churned)' =
			
			FORMAT(
			    CALCULATE(AVERAGE(dim_customer[Tenure_Months]), fact_churn[Churn_Updated] = "Churned"), "0")
		displayFolder: Tenure
		lineageTag: 494be658-6219-491c-a3db-817b11cd9b54

	measure 'Highest Churn Tenure Band Label' = ```
			
			VAR MaxChurnRate = 
			    MAXX(
			        VALUES('dim_customer'[Tenure_band]),
			        [Churn Rate%]
			    )
			
			RETURN
			    UNICHAR(11166) & " Customers in months " & [Highest Churn Tenure Band] & " churn at " & FORMAT(MaxChurnRate,"0.00%")
			```
		displayFolder: Tenure
		lineageTag: 141bbe74-73b5-4b42-8fef-7ca5b95097a3

	measure 'Fibre Optics Churn Rate' = ```
			
			CALCULATE( [Churn Rate%], dim_services[Internet_Service_Type_Updated] = " Fiber Optic " )
			
			```
		displayFolder: Services
		lineageTag: c8ff7415-e33c-43c5-ba60-53db2efc06d5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Dynamic Space Measure For Bar Chart(Internet Service Type)' =
			
			MAXX(VALUES(dim_services[Internet_Service_Type_Updated]),[% of Total Customers]) * 1.3
		displayFolder: Services
		lineageTag: c02933e1-f6fb-4f6c-8b97-fe7f5dd1a620

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Dynamic Space Measure For Amount Lost bar Chart(Internet Service Type)' =
			
			MAXX(VALUES(dim_services[Internet_Service_Type_Updated]),[Amount Lost(Monthly) to Churn]) * 1.2
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Services
		lineageTag: 9032ab3c-26f8-4979-b588-b6c00fcc49a4

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Dynamic Space Measure For Bar Chart(Has Device Protection)' =
			
			MAXX(VALUES(dim_services[Has_Device_Protection]), [Churn Rate%]) * 1.3
		displayFolder: Services
		lineageTag: b738c44a-4cf5-4258-82c9-75bd2e1c556a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Dynamic Space Measure For Bar Chart(Has Online Security)' =
			
			MAXX(VALUES(dim_services[Has_Online_Security]), [Churn Rate%]) * 1.3
		displayFolder: Services
		lineageTag: 6ce9ab80-a706-4dee-a756-790c4f2e5840

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Dynamic Space Measure For Bar Chart(Has Tech Support)' =
			
			MAXX(VALUES(dim_services[Has_Tech_Support]), [Churn Rate%]) * 1.3
		displayFolder: Services
		lineageTag: 29ec0902-b6cb-4087-a66a-dea1478d5e08

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Dynamic Space Measure For Bar Chart(Has Online Backup)' =
			
			MAXX(VALUES(dim_services[Has_Online_Backup]), [Churn Rate%]) * 1.3
		displayFolder: Services
		lineageTag: 7a8a58bf-338e-4ef9-895c-856e9eafd1c6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Dynamic Space Measure For Bar Chart(Amount Lost(Monthly) to Churn)' =
			
			MAXX(VALUES(dim_services[Internet_Service_Type_Updated]),[Amount Lost(Monthly) to Churn]) * 1.3
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Services
		lineageTag: 69033924-ff25-474f-815e-64a54e3b3682

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 100% = 100
		formatString: 0
		displayFolder: Labels & Formatting
		lineageTag: a7ed2885-a306-4db4-9cec-a54edfe79bcf

	measure 'Dynamic Space Measure For Bar Chart(Streaming Movies)' =
			
			MAXX(VALUES(dim_services[Has_Streaming_Movies]),[Churn Rate%]) * 1.45
		displayFolder: Services
		lineageTag: d81a3415-36b1-4a9b-94a3-5ec32971ac29

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Percentage of total revenue amount that was lost to churned customers. Similar to '% of All Churned Customers' but measures revenue impact instead of customer count.
	measure '% of Amount Churned' =
			// Calculates the percentage of total revenue amount that was lost to churn
			// VAR Total_Amount = CALCULATE(SUM(fact_churn[Total_Charge_USD]), REMOVEFILTERS(dim_customer))
			// VAR Churned_Amount = CALCULATE(SUM(fact_churn[Total_Charge_USD]), REMOVEFILTERS(dim_customer), fact_churn[Churned] = 1)
			// VAR Pct_Amount_Churned = DIVIDE(Churned_Amount, Total_Amount)
			
			// RETURN
			//     Pct_Amount_Churned
			
			VAR Total_Amount_Churned = CALCULATE([Amount Lost(Monthly) to Churn], ALL(dim_customer))
			VAR Churned_Amount = [Amount Lost(Monthly) to Churn]
			VAR Pct_Amount_Churned = DIVIDE( Churned_Amount, Total_Amount_Churned)
			
			RETURN
			Pct_Amount_Churned
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Financial Impact
		lineageTag: 25362ea8-cd8c-427d-9339-1989e0c704fb

	/// Color measure for % of Amount Churned by Internet Type. Returns red if >= 50%, grey otherwise.
	measure '% of Amount Churned Color' =
			// Color measure for % of Amount Churned - Returns red if >= 50%, grey otherwise
			VAR Current_Pct = [% of Amount Churned]
			
			RETURN
			    IF(Current_Pct >= 0.5, "#E81B23", "#A6A6A6")
		displayFolder: Financial Impact
		lineageTag: 9c72672d-632c-4611-bc0f-82f7663d6b50

	measure Fiber_vs_DSL_Multiplier =
			
			VAR Fiber_Churn_Rate = CALCULATE( [Churn Rate%], dim_services[Internet_Service_Type_Updated] = "Fiber Optic" )
			VAR DSL_Churn_Rate = CALCULATE( [Churn Rate%], dim_services[Internet_Service_Type_Updated] = "DSL" )
			
			RETURN
			FORMAT(DIVIDE( Fiber_Churn_Rate, DSL_Churn_Rate, 0), "0.00\x")
		displayFolder: Services
		lineageTag: ff23aa29-1676-436c-a6b7-bc38bb0afafd

	measure 'Fiber vs No Internet Churn Multiple' =
			
			
			VAR Fiber_Churn_Rate = CALCULATE( [Churn Rate%], dim_services[Internet_Service_Type_Updated] = "Fiber Optic" )
			VAR No_Internet_Churn_Rate = CALCULATE( [Churn Rate%], dim_services[Internet_Service_Type_Updated] = "No internet" )
			
			RETURN
			FORMAT(DIVIDE( Fiber_Churn_Rate, No_Internet_Churn_Rate, 0), "0.00\x")
		displayFolder: Services
		lineageTag: 551aa1e3-d8fa-42f5-8bc6-2bc15d761e8a

	measure 'Fiber Optic Churn Amount' = ```
			
			    FORMAT(ROUND(CALCULATE([Amount Lost(Monthly) to Churn] , dim_services[Internet_Service_Type_Updated] = "Fiber Optic"), -3),"$#,##0,\k")
			    
			```
		displayFolder: Services
		lineageTag: 4feede39-982c-4da5-8e55-bb00ba80b2a0

	/// Percentage of churned customers that have Fiber Optic internet service
	measure '% of Churned Customers from Fiber Optics' =
			// Calculates the percentage of churned customers that are from Fiber Optics
			VAR Churned_Fiber_Customers = CALCULATE(
			    [Churned Customers],
			    dim_services[Internet_Service_Type_Updated]= "Fiber Optic"
			)
			VAR Total_Churned = [Churned Customers]
			VAR Pct_Churned_Fiber = DIVIDE(Churned_Fiber_Customers, Total_Churned)
			
			RETURN
			    Pct_Churned_Fiber
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Services
		lineageTag: 48d898f7-27bd-484d-b492-26188b33cd0b

	/// Percentage of total monthly churn amount contributed by Fiber Optic customers
	measure '% of Monthly Churn Amount from Fiber Optics' =
			// Calculates the percentage of total monthly churn amount from Fiber Optic customers
			VAR Churned_Fiber_Monthly = CALCULATE(
			[Amount Lost(Monthly) to Churn],
			    dim_services[Internet_Service_Type_Updated] = "Fiber Optic"
			)
			VAR Total_Churned_Monthly = [Amount Lost(Monthly) to Churn]
			VAR Pct_Amount_Churned_Fiber = DIVIDE(Churned_Fiber_Monthly, Total_Churned_Monthly)
			
			RETURN
			    Pct_Amount_Churned_Fiber
		formatString: 0%;-0%;0%
		displayFolder: Services
		lineageTag: 47fd8806-5a77-4e8d-acc0-c7fcf204adfa

	/// Percentage drop in churn rate between customers without and with online security
	measure 'Churn Rate % Drop (Online Security)' = ```
			// Calculates the percentage drop in churn rate between no online security vs has online security
			VAR Churn_Without_Security = CALCULATE(
			    [Churn Rate%],
			    dim_services[Has_Online_Security]= "No"
			)
			VAR Churn_With_Security = CALCULATE(
			    [Churn Rate%],
			    dim_services[Has_Online_Security] = "Yes"
			)
			VAR Pct_Drop = 
			FORMAT(DIVIDE(
			    Churn_Without_Security - Churn_With_Security,
			    Churn_Without_Security), "-0.00%") 
			
			
			RETURN
			  Pct_Drop  &    UNICHAR(11015)
			```
		displayFolder: Services
		lineageTag: 97f9a125-6029-4c08-b451-6744d734fbea

	/// Multiplier showing how many times higher the churn rate is for customers without vs with online security
	measure 'Churn Rate Multiplier (Online Security)' =
			// Calculates the multiplier (ratio) between churn rate without and with online security
			VAR Churn_Without_Security = CALCULATE(
			    [Churn Rate%],
			    dim_services[Has_Online_Security] = "No"
			)
			VAR Churn_With_Security = CALCULATE(
			    [Churn Rate%],
			    dim_services[Has_Online_Security] = "Yes"
			)
			VAR Multiplier = FORMAT(DIVIDE(Churn_Without_Security, Churn_With_Security), "0.00""x⬆""")
			
			RETURN
			    Multiplier
		displayFolder: Services
		lineageTag: d9d44870-887b-4f36-b2f9-468ebbb1b3af

	/// Percentage of total customer base that have Fiber Optic internet service
	measure '% of Customer Base from Fiber Optics' =
			// Calculates the percentage of customers with Fiber Optic internet service
			VAR Fiber_Customers = CALCULATE(
			    [Total Number of Customers],
			    dim_services[Internet_Service_Type_Updated] = "Fiber Optic"
			)
			VAR Total_Customers = [Total Number of Customers]
			VAR Pct_Fiber_Customers = FORMAT(DIVIDE(Fiber_Customers, Total_Customers), "0%")
			
			RETURN
			    Pct_Fiber_Customers & " of customers base"
		displayFolder: Services
		lineageTag: b96f247b-d897-46c4-9a8f-19c924248b30

	measure 'Fiber Churn Pct Revenue Loss label' = ```
			
			    VAR FiberLoss = [Fiber Optic Churn Amount]
			
			    VAR TotalAmount = FORMAT([Amount Lost(Monthly) to Churn],"$#,##0,\k")
			
			    RETURN
			    FiberLoss & " of " & TotalAmount & " monthly"
			```
		displayFolder: Services
		lineageTag: 5c909c62-ff29-4db7-8785-4ca4aa4d0b52

	measure 'Churn Drop without Online Security' = ```
			
			    VAR WithoutChurnPct = FORMAT(CALCULATE( [Churn Rate%], dim_services[Has_Online_Security] = "No" ), "0.00%")
			    VAR WithChurnPct = FORMAT(CALCULATE( [Churn Rate%], dim_services[Has_Online_Security] = "Yes" ), "0.00%")
			
			    RETURN
			   "w/o: " &  WithoutChurnPct & " " & UNICHAR(8594) &  " w: " &   WithChurnPct 
			
			
			```
		displayFolder: Services
		lineageTag: 44401af5-cac9-41d8-ab49-aa7f49b63b3e

	measure 'Churn Rate Multiplier (Online Security) Label' = ```
			
			"Largest risk factor" 
			```
		displayFolder: Services
		lineageTag: 8d3beb70-9355-4911-8aa7-7403e7ca79d0

	/// Churn rate for customers WITHOUT a selected service, using Driver Table for dynamic service selection
	measure 'Churn Rate Without Service' =
			// Dynamic churn rate for customers without a selected service
			VAR DriverSelected =
			    SELECTEDVALUE('Driver Table'[Driver])
			
			RETURN
			SWITCH(
			    DriverSelected,
			
			    "Online Security",
			        CALCULATE(
			            [Churn Rate%],
			            dim_services[Has_Online_Security] = "No"
			        ),
			
			    "Tech Support",
			        CALCULATE(
			            [Churn Rate%],
			            dim_services[Has_Tech_Support] = "No"
			        ),
			
			    "Online Backup",
			        CALCULATE(
			            [Churn Rate%],
			            dim_services[Has_Online_Backup] = "No"
			        ),
			
			    "Device Protection",
			        CALCULATE(
			            [Churn Rate%],
			            dim_services[Has_Device_Protection] = "No"
			        ),
			
			    "Streaming TV",
			        CALCULATE(
			            [Churn Rate%],
			            dim_services[Has_Streaming_TV] = "No"
			        ),
			
			    "Streaming Movies",
			        CALCULATE(
			            [Churn Rate%],
			            dim_services[Has_Streaming_Movies] = "No"
			        )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Services
		lineageTag: 0f97b210-1af9-4c3e-8e21-3cba96e6e777

	/// Churn rate for customers WITH a selected service, using Driver Table for dynamic service selection
	measure 'Churn Rate With Service' =
			// Dynamic churn rate for customers with a selected service
			VAR DriverSelected =
			    SELECTEDVALUE('Driver Table'[Driver])
			
			RETURN
			SWITCH(
			    DriverSelected,
			
			    "Online Security",
			        CALCULATE(
			            [Churn Rate%],
			            dim_services[Has_Online_Security] = "Yes"
			        ),
			
			    "Tech Support",
			        CALCULATE(
			            [Churn Rate%],
			            dim_services[Has_Tech_Support] = "Yes"
			        ),
			
			    "Online Backup",
			        CALCULATE(
			            [Churn Rate%],
			            dim_services[Has_Online_Backup] = "Yes"
			        ),
			
			    "Device Protection",
			        CALCULATE(
			            [Churn Rate%],
			            dim_services[Has_Device_Protection] = "Yes"
			        ),
			
			    "Streaming TV",
			        CALCULATE(
			            [Churn Rate%],
			            dim_services[Has_Streaming_TV] = "Yes"
			        ),
			
			    "Streaming Movies",
			        CALCULATE(
			            [Churn Rate%],
			            dim_services[Has_Streaming_Movies] = "Yes"
			        )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Services
		lineageTag: c21258ff-bbd4-42ef-b6d7-00e22a471250

	measure 'Reduction %' =
			
			-DIVIDE(
			    [Churn Rate Without Service] -
			    [Churn Rate With Service],
			    [Churn Rate Without Service]
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Services
		lineageTag: 72b68cdf-a2ed-42ed-9ae6-07012f50eb62

	measure 'Top Churn Drivers Color' = ```
			
			    IF( [Reduction %] > 0, "#C73030", "#0B6112")
			```
		displayFolder: Services
		lineageTag: 0bd2258c-bd74-4393-ae25-c5ee5b089c6f

	measure 'Electronic Check Pct of Customer Base' = ```
			
			    CALCULATE([% of Total Customers], dim_billing[Payment_Method] = "Electronic Check")
			```
		displayFolder: Contract & Billing
		lineageTag: b440b0ff-21fa-4899-80b2-0b590ffa190f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MTM Pct of Churn Customers' = ```
			
			    CALCULATE( [% of All Churned Customers], dim_billing[Contract_Type] = "Month-to-Month")
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Contract & Billing
		lineageTag: 515b9eca-0b58-4b41-81a4-8dddf7160d31

	measure 'MTM Pct of Customer Base' = ```
			
			    CALCULATE([% of Total Customers], dim_billing[Contract_Type] = "Month-to-Month")
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Contract & Billing
		lineageTag: 3017a6dd-48dd-4d37-b3dd-b73e5a6c6664

	measure 'MTM Pct Churn Label' = ```
			
			    FORMAT([MTM Pct of Customer Base], "0%") & " of customer base"
			```
		displayFolder: Contract & Billing
		lineageTag: 14ae61df-1e77-4f85-ab2b-64b93987d6f0

	measure 'MTM Pct Revenue Loss' = ```
			
			    CALCULATE([% of Amount Churned], dim_billing[Contract_Type] = "Month-to-Month")
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Contract & Billing
		lineageTag: cd5d6beb-324a-4eea-8a73-c7f442d4068d

	measure 'MTM Pct Revenue Loss Label' = ```
			
			    Var MTM_loss = CALCULATE([Amount Lost(Monthly) to Churn], dim_billing[Contract_Type] = "Month-to-Month")
			
			    RETURN
			    FORMAT(MTM_loss,"$#,##0,K") & " of " & FORMAT([Amount Lost(Monthly) to Churn], "$#,##0,K") & " lost"
			```
		displayFolder: Contract & Billing
		lineageTag: 5dc6f37a-bdc8-4558-9fec-2c0257231373

	measure 'Electronic Check Pct of Churn Customers' = ```
			
			    CALCULATE( [% of All Churned Customers], dim_billing[Payment_Method] = "Electronic Check")
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Contract & Billing
		lineageTag: 45c37fc7-9961-4795-8ecc-7d48bfb54b7c

	measure 'Electronic Check Pct Churn Customers Label' = ```
			
			    FORMAT([Electronic Check Pct of Customer Base], "0%") & " of customer base"
			```
		displayFolder: Contract & Billing
		lineageTag: cbfc5862-d1a7-49ac-b773-b59100d38e31

	/// Multiplier showing how many times higher the churn rate is for traditional billing vs paperless billing customers
	measure 'Churn Rate Multiplier (Paperless Billing)' =
			// Calculates the multiplier (ratio) between churn rate for traditional billing vs paperless billing
			VAR Churn_Traditional_Billing = CALCULATE(
			    [Churn Rate%],
			    dim_billing[Uses_Paperless_Billing] = 0
			)
			VAR Churn_Paperless_Billing = CALCULATE(
			    [Churn Rate%],
			    dim_billing[Uses_Paperless_Billing] = 1
			)
			VAR Multiplier = FORMAT(DIVIDE(Churn_Paperless_Billing, Churn_Traditional_Billing),"0.00""x⬆""")
			
			RETURN
			    Multiplier
		displayFolder: Contract & Billing
		lineageTag: ac9bba66-90f7-4272-8482-40c5b2545a05

	measure 'Churn Rate Multiplier (Paperless Billing) Label' =
			
			"Risk indicator, not cause"
		displayFolder: Contract & Billing
		lineageTag: e8ccdf05-9e04-4263-93e8-cc7ec798d3fb

	measure 'Dynamic Space for Column chart Churn Rate ( Contract Type )' =
			
			MAXX(VALUES(dim_billing[Contract_Type]), [Churn Rate%]) * 1.4
		displayFolder: Contract & Billing
		lineageTag: d690c614-67dc-4adb-8f46-6e40d2127511

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Dynamic Space for Column chart Amount Churned ( Contract Type )' =
			
			MAXX(VALUES(dim_billing[Contract_Type]), [Amount Lost(Monthly) to Churn]) * 1.4
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Contract & Billing
		lineageTag: 753f918c-433a-4d56-865b-9840c4a8b162

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Dynamic Space for Bar chart(Payment Method)' = ```
			
			    MAXX(VALUES(dim_billing[Payment_Method_Cleaned]), [Churn Rate%]) * 1.4
			```
		displayFolder: Contract & Billing
		lineageTag: 34f4d9bf-66f8-41e4-8426-ae030caf3ea8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Payment Method Relative Risk' = ```
			
			   // Calculates Lowest Churn
			    VAR lowestChurnRate =  CALCULATE(MINX(VALUES(dim_billing[Payment_Method_Cleaned]), [Churn Rate%]), REMOVEFILTERS(dim_billing[Payment_Method_Cleaned]))
			    // Returns Churn Category
			    VAR CurrentChurnRate = [Churn Rate%]
			    // Calculates Relativity
			    VAR Relativity = 
			        DIVIDE( CurrentChurnRate, lowestChurnRate,0)
			
			    RETURN
			    Relativity
			```
		formatString: 0.00x
		displayFolder: Contract & Billing
		lineageTag: e235ac9d-4319-464f-a04a-930a8dca60a0

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Risk Level Payment Method' = ```
			
			VAR CurrentRisk = [Payment Method Relative Risk]
			RETURN
			    SWITCH(
			        TRUE(),
			        CurrentRisk <= 1.00, "Lowest",
			        CurrentRisk <= 1.10, "Low",       CurrentRisk <= 1.5, "Moderate",
			    "Highest"
			    )
			
			```
		displayFolder: Contract & Billing
		lineageTag: 79bfb17b-fee5-478c-8a31-d48780d64fb7

	/// Churn rate for customers using traditional (non-paperless) billing
	measure 'Churn Rate - Traditional Billing' =
			// Churn rate for customers with traditional billing
			CALCULATE(
			    [Churn Rate%],
			    dim_billing[Uses_Paperless_Billing] = 0
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Contract & Billing
		lineageTag: 5ee0b695-3f61-4e54-9511-f7c068049b77

	/// Churn rate for customers using paperless billing
	measure 'Churn Rate - Paperless Billing' =
			// Churn rate for customers with paperless billing
			CALCULATE(
			    [Churn Rate%],
			    dim_billing[Uses_Paperless_Billing] = 1
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Contract & Billing
		lineageTag: b2a2b14d-db37-4c48-ba4f-7c3782f05ab6

	measure 'MAxx Billing' = ```
			
			   CALCULATE( MAXX(VALUES(dim_billing[Uses Paper Billing Updated]), [Churn Rate%]), REMOVEFILTERS(dim_billing[Uses Paper Billing Updated]))
			```
		displayFolder: Contract & Billing
		lineageTag: 6bfaad5c-c70a-490c-805b-94f7b09a0463

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Churn Rate Multiplier (Paperless Billing) 2' =
			// Calculates the multiplier (ratio) between churn rate for traditional billing vs paperless billing
			VAR Churn_Traditional_Billing = CALCULATE(
			    [Churn Rate%],
			    dim_billing[Uses_Paperless_Billing] = 0
			)
			VAR Churn_Paperless_Billing = CALCULATE(
			    [Churn Rate%],
			    dim_billing[Uses_Paperless_Billing] = 1
			)
			VAR Multiplier = FORMAT(DIVIDE(Churn_Paperless_Billing, Churn_Traditional_Billing),"0.00""x""")
			
			RETURN
			    Multiplier
		displayFolder: Contract & Billing
		lineageTag: b6e29ecb-f0fc-4b3b-891c-36e8be40a817

	measure Measure
		displayFolder: Contract & Billing
		lineageTag: 37e18b3f-27b2-4d6b-8f66-2f635743af0a

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure 'Type of billing color'
		displayFolder: Contract & Billing
		lineageTag: 2d4e9659-07cd-4248-bb3d-2232feff6552

	/// Color measure for payment method based on risk level. Lowest/Low = Green, Moderate = Orange, Highest = Red
	measure 'Payment Method Risk Level Color' =
			// Color measure for payment method risk level
			VAR RiskLevel = [Risk Level Payment Method]
			
			RETURN
			    SWITCH(
			        RiskLevel,
			        "Lowest", "#70AD47",        // Lowest Risk - Green
			        "Low", "#70AD47",            // Low Risk - Green
			        "Moderate", "#FFA500",       // Moderate Risk - Orange
			        "Highest", "#E81B23",        // Highest Risk - Red
			        "#D5DBED"                    // Default - Light Grey
			    )
		displayFolder: Contract & Billing
		lineageTag: 9d5ef890-1495-42ab-b2fc-befead6a4e11

	/// Color measure for retention opportunities impact level. Very High/High = Green, Medium = Orange, Low = Red
	measure 'Retention Opportunity Impact Color' =
			// Color measure for retention opportunities impact level
			VAR ImpactLevel = SELECTEDVALUE('Retention Opportunites'[Impact])
			
			RETURN
			    SWITCH(
			        ImpactLevel,
			        "Very High", "#70AD47",     // Very High Impact - Green
			        "High", "#70AD47",           // High Impact - Green
			        "Medium", "#FFA500",         // Medium Impact - Orange
			        "Low", "#E81B23",            // Low Impact - Red
			        "#D5DBED"                    // Default - Light Grey
			    )
		displayFolder: Labels & Formatting
		lineageTag: 0f714a5f-a9dc-46f5-809a-6157fdb87f60

	/// Relativity multiplier between Electronic Check and Bank Transfer churn rates
	measure 'Electronic Check vs Bank Transfer Relativity' =
			// Calculates how many times higher Electronic Check churn is vs Bank Transfer
			VAR Electronic_Check_Churn = CALCULATE(
			    [Churn Rate%],
			    dim_billing[Payment_Method_Cleaned] = "electronic check"
			)
			VAR Bank_Transfer_Churn = CALCULATE(
			    [Churn Rate%],
			    dim_billing[Payment_Method_Cleaned] = "bank transfer"
			)
			VAR Relativity = DIVIDE(Electronic_Check_Churn, Bank_Transfer_Churn)
			
			RETURN
			    Relativity
		formatString: 0.00x
		displayFolder: Contract & Billing
		lineageTag: 441776f6-e4cd-487a-a075-6ee3f2f719e6

	/// Relativity multiplier between Electronic Check and Credit Card churn rates
	measure 'Electronic Check vs Credit Card Relativity' =
			// Calculates how many times higher Electronic Check churn is vs Credit Card
			VAR Electronic_Check_Churn = CALCULATE(
			    [Churn Rate%],
			    dim_billing[Payment_Method_Cleaned] = "electronic check"
			)
			VAR Credit_Card_Churn = CALCULATE(
			    [Churn Rate%],
			    dim_billing[Payment_Method_Cleaned] = "credit card"
			)
			VAR Relativity = DIVIDE(Electronic_Check_Churn, Credit_Card_Churn)
			
			RETURN
			    Relativity
		formatString: 0.00x
		displayFolder: Contract & Billing
		lineageTag: 747248f6-96bb-4cc7-9fee-421498ff652a

	/// Percentage of total customer base in the current segment or dimension
	measure '% of Base Customers' = ```
			// Calculates the percentage of customers in the current segment relative to total customer base
			VAR Current_Segment_Customers = [Total Number of Customers]
			VAR Total_Base_Customers = CALCULATE(
			    [Total Number of Customers], ALL(dim_customer)
			)
			VAR Pct_Of_Base = DIVIDE(Current_Segment_Customers, Total_Base_Customers)
			
			RETURN
			    Pct_Of_Base
			
			    
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Core KPIs
		lineageTag: d083c711-2d0d-4dca-aeea-d6d17e1d5cbd

	measure 'Churn Rate% 2' =
			
			[Churn Rate%]
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Labels & Formatting
		lineageTag: a77a9f14-f866-493c-ae79-b36853e56ee0

	measure 'Charge Band Color' = ```
			
			VAR MaxChurn = 
			    CALCULATE(
			        MAXX(
			            VALUES(dim_billing[Charge Band Monthly]), 
			            [Churn Rate%]
			        ), 
			        REMOVEFILTERS(
			            dim_billing[Charge Band Monthly], 
			            dim_billing[Charge Band Sort Column] -- Removes the hidden sort filter
			        )
			    )
			
			RETURN
			    IF( [Churn Rate%] < MaxChurn,  "#D5DBED
			","#343C53
			")
			
			```
		displayFolder: Charge Bands
		lineageTag: acca48b7-e734-47c5-8177-4b5ec97d3d65

	measure 'Measure 3'
		displayFolder: Charge Bands
		lineageTag: 76baedd3-beda-47cd-a2f0-c326c3032a9a

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure 'Data Bar Graphic' = ```
			
			// VAR BarLength = ROUND([Churn Rate%] * 43, 0) -- Adjust multiplier to fit your column width
			// RETURN
			//     REPT("█", BarLength)
			
			
			-- 1. Find the highest churn rate across all charge bands (accounting for the sort column)
			VAR MaxChurn = 
			    CALCULATE(
			        [Churn Rate%], 
			        TOPN(1, ALL(dim_billing[Charge Band Monthly], dim_billing[Charge Band Sort Column]), [Churn Rate%], DESC)
			    )
			
			-- 2. Define how many blocks long the LARGEST bar should be (e.g., 15 blocks wide)
			VAR MaxBarLength = 8
			
			-- 3. Calculate this row's length proportional to the maximum value
			VAR CurrentBarLength = 
			    IF(
			        NOT(ISBLANK([Churn Rate%])) && MaxChurn > 0,
			        ROUND(([Churn Rate%] / MaxChurn) * MaxBarLength, 0),
			        0
			    )
			
			RETURN
			    REPT("█", CurrentBarLength)
			
			```
		displayFolder: Charge Bands
		lineageTag: 415fce45-86fc-40c8-8500-d9ce72507361

	measure 'Charge Band Color(Font)' = ```
			
			VAR MaxChurn = 
			    CALCULATE(
			        MAXX(
			            VALUES(dim_billing[Charge Band Monthly]), 
			            [Churn Rate%]
			        ), 
			        REMOVEFILTERS(
			            dim_billing[Charge Band Monthly], 
			            dim_billing[Charge Band Sort Column] -- Removes the hidden sort filter
			        )
			    )
			
			RETURN
			    IF( [Churn Rate%] < MaxChurn,  "#9599a6
			","#151618")
			
			```
		displayFolder: Charge Bands
		lineageTag: 513ee854-51b0-4026-abf2-d54811f21813

	measure 'Retained Average Charge' = ```
			
			    CALCULATE([Average Monthly Charge], 'fact_churn'[Churn_Updated] = "Retained")
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Financial Impact
		lineageTag: 76dda739-fadd-4259-bb1d-25c54630776f

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Churned Average Charge' =
			
			CALCULATE([Average Monthly Charge], fact_churn[Churn_Updated] = "Churned")
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Financial Impact
		lineageTag: 5e293be8-e451-4d99-a406-9219c2f8e8f5

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Average Pricing Gap' = ```
			
			   VAR PriceGap = ( [Churned Average Charge] - [Retained Average Charge])
			
			   RETURN
			    IF( PriceGap > 0,
			        "+"&PriceGap, "-"&PriceGap
			    )
			```
		formatString: General
		displayFolder: Financial Impact
		lineageTag: 4890c45c-2bd6-454b-bdd4-cf24e9d43e1f

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Avg Lifetime Charge - Retained' =
			
			CALCULATE(
			    AVERAGE(fact_churn[Total_Charge_USD]),
			    fact_churn[Churn_Updated] = "Retained"
			)
		displayFolder: Financial Impact
		lineageTag: 8462eb8a-b620-4ba6-a1fe-4aeb659de71e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Lifetime Charge - Churned' =
			
			CALCULATE(
			    AVERAGE(fact_churn[Total_Charge_USD]),
			    fact_churn[Churn_Updated] = "Churned"
			)
		displayFolder: Financial Impact
		lineageTag: 1b191eb6-2a92-4c60-bafc-eb078f688d04

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Lifetime Value Gap' =
			
			[Avg Lifetime Charge - Retained] - [Avg Lifetime Charge - Churned]
		displayFolder: Financial Impact
		lineageTag: 924ec9f3-14e2-4e43-8c6d-939fab6333cd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Monthly Charge Premium' =
			
			+([Avg Monthly Charge - Churned] - [Avg Monthly Charge - Retained])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Financial Impact
		lineageTag: 5e4aedca-1692-47ed-aa42-9f4f5a5b21aa

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Avg Monthly Charge - Retained' =
			
			CALCULATE(
			    [Average Monthly Charge], fact_churn[Churn_Updated] = "Retained"
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Financial Impact
		lineageTag: f48d5a52-5564-44cf-af86-83de95d0d1de

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Avg Monthly Charge - Churned' =
			
			CALCULATE(
			    [Average Monthly Charge], fact_churn[Churn_Updated] = "Churned"
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Financial Impact
		lineageTag: c3b86dda-a5e2-4163-920f-63a2387f2ef8

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Monthly Charge Premium Label' = ```
			
			    FORMAT([Avg Monthly Charge - Churned], "$0.00") & " vs " & FORMAT([Avg Monthly Charge - Retained], "$0.00")
			```
		displayFolder: Financial Impact
		lineageTag: 1ead03f7-a396-416a-8410-af2ca4ca0b16

	measure 'Charge Band Max Churn Rate%' = ```
			
			    MAXX(VALUES(dim_billing[Charge Band Monthly]), [% of Amount Churned])
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Charge Bands
		lineageTag: ad023d8b-aee7-43a6-9ccd-7a17bcd9fbd9

	measure 'Annual Revenue Loss' = ```
			
			[Amount Lost(Monthly) to Churn] * 12 
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Core KPIs
		lineageTag: 534f8b6b-bdf5-4115-935d-e54c463044f9

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Churn Exceeds Average Above $60' = "$60"
		displayFolder: Charge Bands
		lineageTag: 46213a38-c427-44b0-8c75-3b4422be2a04

	measure 'Dynamic Space Measure For Column Chart(Average Price)' =
			
			MAXX(VALUES(fact_churn[Churn_Updated]),[Average Monthly Charge]) * 1.5
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Charge Bands
		lineageTag: 83296651-a712-4ae4-aa81-4093943b4dc8

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Measure 4'
		displayFolder: Charge Bands
		lineageTag: 60e8f612-468c-40fb-8980-ff9c3e05715a

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure 'Lifetime Value Premium %' =
			
			DIVIDE(
			    [Lifetime Value Gap],
			    [Avg Lifetime Charge - Churned],
			    0
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Financial Impact
		lineageTag: f6ca2dfb-4d8e-4374-b3e0-4be0c3ac1993

	measure 'Dynamic Space Measure For Bar Chart(Amount Lost(Monthly) to Churn/ Charged Monthly)' =
			
			MAXX(VALUES(dim_billing[Charge Band Monthly]),[Amount Lost(Monthly) to Churn]) * 1.1
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Charge Bands
		lineageTag: 6d7991ee-18a6-4d9b-85bb-aaa382f49637

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure '% of Amount Churned Color ( Charge Band ) Color_Bars' = ```
			
			    Var MaxPct = CALCULATE(MAXX(VALUES(dim_billing[Charge Band Monthly]),[% of Amount Churned]), REMOVEFILTERS(dim_billing))
			    Var CurrentPct = [% of Amount Churned]
			RETURN
			IF(MaxPct = CurrentPct, "#343C53", "#D5DBED")
			```
		displayFolder: Charge Bands
		lineageTag: 2b735409-624a-428d-b3ce-128f45ee0524

	measure '% of Amount Churned Color ( Charge Band ) Color_Text' = ```
			
			    Var MaxPct = CALCULATE(MAXX(VALUES(dim_billing[Charge Band Monthly]),[% of Amount Churned]), REMOVEFILTERS(dim_billing))
			    Var CurrentPct = [% of Amount Churned]
			RETURN
			IF(MaxPct = CurrentPct,"#C73030", "#343C53")
			```
		displayFolder: Charge Bands
		lineageTag: acaff6bb-7a25-45c4-88d1-cd87ce9cfc33

	measure 'Avg Lifetime Charge' = ```
			
			
			    AVERAGE(fact_churn[Total_Charge_USD])
			    
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Financial Impact
		lineageTag: 25609f95-f6ad-45a7-92b2-ee471544f875

	measure 'Dynamic Space Measure For Column Chart(Average Lifetime Value)' =
			
			MAXX(VALUES(fact_churn[Churn_Updated]),[Avg Lifetime Charge]) * 1.5
		displayFolder: Charge Bands
		lineageTag: fdeac4f5-5156-4c4c-909f-195098bca269

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Dynamic Space Measure For Column Chart(Churn Rate/ Charged Monthly)' =
			
			MAXX(VALUES(dim_billing[Charge Band Monthly]),[Churn Rate%]) * 1.2
		displayFolder: Charge Bands
		lineageTag: d6acddfc-1ccc-40ee-9f4d-a98a61a24592

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Churn Rate Color ( Charge Band ) Color_Text' = ```
			
			    Var MaxPct = CALCULATE(MAXX(VALUES(dim_billing[Charge Band Monthly]),[Churn Rate%]), REMOVEFILTERS(dim_billing))
			    Var CurrentPct = [Churn Rate%]
			RETURN
			IF(MaxPct = CurrentPct, "#C73030", "#343C53")
			```
		displayFolder: Charge Bands
		lineageTag: 49279a14-37f7-40a9-a159-4fe51da48c68

	measure 'Largest Revenue Label' = "$81-$100 charge band"
		displayFolder: Charge Bands
		lineageTag: be12b5a5-c07a-4de8-9088-06502ffb948a

	measure 'Risk rises beyond this level' = "Risk rises beyond this level"
		displayFolder: Charge Bands
		lineageTag: c76c3a82-a2d4-4ecd-b7b9-27c3dd6915c0

	measure 'Total Monthly Revenue' =
			
			SUM(dim_billing[Monthly_Charge_USD])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Core KPIs
		lineageTag: 2438e28f-ef54-4797-9a42-41ff40500701

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Revenue Loss %' = ```
			
			    VAR AmountLost = [Amount Lost(Monthly) to Churn]
			    VAR TotalRevenue = CALCULATE([Total Monthly Revenue], ALL(dim_billing))
			    VAR pct = FORMAT(DIVIDE(AmountLost, TotalRevenue), "0.0%")
			
			    RETURN
			    pct& " of monthly revenue"
			
			```
		displayFolder: Core KPIs
		lineageTag: 2acc8709-ff7f-4daf-9386-6849aaae95a1

	column Driver
		lineageTag: c0118fc1-7c3f-4216-b82a-22f52dbf2470
		summarizeBy: none
		isNameInferred
		sourceColumn: Driver Table[Driver]

		annotation SummarizationSetBy = Automatic

	column 'Sort Order'
		formatString: 0
		lineageTag: cfcdd016-6ab6-4b05-8a04-43f531a772b8
		summarizeBy: sum
		isNameInferred
		sourceColumn: Driver Table[Sort Order]

		annotation SummarizationSetBy = Automatic

	partition 'Measure Table' = calculated
		mode: import
		source = ```
				'Driver Table'
				
				    
				```

